### ISSUE TITLE
Cetora key for testing

### ISSUE THREAD

**Issue by Jesserc** [Certora/Documentation#103]
Please Can I get a Certora key for testing purposes?
I'm writing a tutorial.

**Comment by urikirsh** [comment]
Hi @Jesserc!
Please join Certora's Discord server - there is a dedicated channel there for key requests.
You can find to the link to Certora's Discord server at certora.com

**Comment by Jesserc** [comment]
> Hi @Jesserc!
> 
> Please join Certora's Discord server - there is a dedicated channel there for key requests.
> 
> You can find to the link to Certora's Discord server at certora.com

Yeah, I'm in the Discord server. 
Just got a response.
